#ifndef BUILDING_H
#define BUILDING_H

#include <string>
class Building {

public:

    enum class Type { Barracks, Farm, Market};  // Types of buildings
    Building(Type type);
    void build();  // Set building status to 'built'
    int getIncome() const;  // Get income generated by the building
    Type getType() const;  // Get the type of the building
    int getCost() const;  // Get the cost of the building
    static std::string buildingTypeToString(Type type) ;
private:
    Type type;
    bool isBuilt;
};

#endif // BUILDING_H
